//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.16 at 11:28:39 AM CET 
//


package eu.gloria.rt.entity.environment.config.device;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for devicePropertyBasicType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="devicePropertyBasicType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="STRING"/>
 *     &lt;enumeration value="INTEGER"/>
 *     &lt;enumeration value="TIME"/>
 *     &lt;enumeration value="DOUBLE"/>
 *     &lt;enumeration value="FLOAT"/>
 *     &lt;enumeration value="BOOL"/>
 *     &lt;enumeration value="SELECTION"/>
 *     &lt;enumeration value="LONGINT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "devicePropertyBasicType")
@XmlEnum
public enum DevicePropertyBasicType {

    STRING,
    INTEGER,
    TIME,
    DOUBLE,
    FLOAT,
    BOOL,
    SELECTION,
    LONGINT;

    public String value() {
        return name();
    }

    public static DevicePropertyBasicType fromValue(String v) {
        return valueOf(v);
    }

}
