//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.16 at 11:28:39 AM CET 
//


package eu.gloria.rt.entity.environment.config.device;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for devicePropertyComplexType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="devicePropertyComplexType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="MMAX"/>
 *     &lt;enumeration value="NONE"/>
 *     &lt;enumeration value="RADEC"/>
 *     &lt;enumeration value="ALTAZ"/>
 *     &lt;enumeration value="STAT"/>
 *     &lt;enumeration value="RECTANGLE"/>
 *     &lt;enumeration value="ARRAY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "devicePropertyComplexType")
@XmlEnum
public enum DevicePropertyComplexType {

    MMAX,
    NONE,
    RADEC,
    ALTAZ,
    STAT,
    RECTANGLE,
    ARRAY;

    public String value() {
        return name();
    }

    public static DevicePropertyComplexType fromValue(String v) {
        return valueOf(v);
    }

}
