//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.16 at 11:28:39 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://gloria.eu/rt/entity/environment/config/device", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.gloria.rt.entity.environment.config.device;
