
package eu.gloria.rti_db;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-09-05T10:52:53.535+02:00
 * Generated source version: 2.6.1
 * 
 */
public final class GloriaRtiDb_GloriaRtiDbSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://gloria.eu/rti_db", "gloria_rti_db");

    private GloriaRtiDb_GloriaRtiDbSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GloriaRtiDb_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GloriaRtiDb_Service ss = new GloriaRtiDb_Service(wsdlURL, SERVICE_NAME);
        GloriaRtiDb port = ss.getGloriaRtiDbSOAP();  
        
        {
        System.out.println("Invoking opGet...");
        java.lang.String _opGet_uuid = "_opGet_uuid-2007973883";
        try {
            eu.gloria.rt.entity.db.ObservingPlan _opGet__return = port.opGet(_opGet_uuid);
            System.out.println("opGet.result=" + _opGet__return);

        } catch (RtiDbError e) { 
            System.out.println("Expected exception: rtiDbError has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking uuidCreate...");
        eu.gloria.rt.entity.db.UuidType _uuidCreate_uuidType = eu.gloria.rt.entity.db.UuidType.OP;
        try {
            java.lang.String _uuidCreate__return = port.uuidCreate(_uuidCreate_uuidType);
            System.out.println("uuidCreate.result=" + _uuidCreate__return);

        } catch (RtiDbError e) { 
            System.out.println("Expected exception: rtiDbError has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking fileAddFormat...");
        java.lang.String _fileAddFormat_uuidFile = "_fileAddFormat_uuidFile-860768944";
        eu.gloria.rt.entity.db.FileFormat _fileAddFormat_format = eu.gloria.rt.entity.db.FileFormat.JPG;
        java.lang.String _fileAddFormat_sourceURL = "_fileAddFormat_sourceURL30489472";
        try {
            port.fileAddFormat(_fileAddFormat_uuidFile, _fileAddFormat_format, _fileAddFormat_sourceURL);

        } catch (RtiDbError e) { 
            System.out.println("Expected exception: rtiDbError has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking opDelete...");
        java.lang.String _opDelete_uuid = "_opDelete_uuid401818738";
        try {
            port.opDelete(_opDelete_uuid);

        } catch (RtiDbError e) { 
            System.out.println("Expected exception: rtiDbError has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking fileDelete...");
        java.lang.String _fileDelete_uuid = "_fileDelete_uuid-1292756376";
        try {
            port.fileDelete(_fileDelete_uuid);

        } catch (RtiDbError e) { 
            System.out.println("Expected exception: rtiDbError has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking fileDeleteFormat...");
        java.lang.String _fileDeleteFormat_uuidFile = "_fileDeleteFormat_uuidFile1913376206";
        eu.gloria.rt.entity.db.FileFormat _fileDeleteFormat_format = eu.gloria.rt.entity.db.FileFormat.JPG;
        try {
            port.fileDeleteFormat(_fileDeleteFormat_uuidFile, _fileDeleteFormat_format);

        } catch (RtiDbError e) { 
            System.out.println("Expected exception: rtiDbError has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking fileGet...");
        java.lang.String _fileGet_uuid = "_fileGet_uuid-1799995065";
        try {
            eu.gloria.rt.entity.db.File _fileGet__return = port.fileGet(_fileGet_uuid);
            System.out.println("fileGet.result=" + _fileGet__return);

        } catch (RtiDbError e) { 
            System.out.println("Expected exception: rtiDbError has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking fileCreate...");
        java.lang.String _fileCreate_uuidOp = "_fileCreate_uuidOp82226390";
        eu.gloria.rt.entity.db.File _fileCreate_file = new eu.gloria.rt.entity.db.File();
        _fileCreate_file.setId("Id1410301480");
        _fileCreate_file.setUuid("Uuid983457765");
        _fileCreate_file.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-09-05T10:52:53.579+02:00"));
        eu.gloria.rt.entity.db.FileContentType _fileCreate_fileContentType = eu.gloria.rt.entity.db.FileContentType.FLAT;
        _fileCreate_file.setContentType(_fileCreate_fileContentType);
        java.util.List<eu.gloria.rt.entity.db.Format> _fileCreate_fileFormats = new java.util.ArrayList<eu.gloria.rt.entity.db.Format>();
        eu.gloria.rt.entity.db.Format _fileCreate_fileFormatsVal1 = new eu.gloria.rt.entity.db.Format();
        eu.gloria.rt.entity.db.FileFormat _fileCreate_fileFormatsVal1FileFormat = eu.gloria.rt.entity.db.FileFormat.JPG;
        _fileCreate_fileFormatsVal1.setFileFormat(_fileCreate_fileFormatsVal1FileFormat);
        _fileCreate_fileFormatsVal1.setUrl("Url-1680373753");
        _fileCreate_fileFormats.add(_fileCreate_fileFormatsVal1);
        _fileCreate_file.getFormats().addAll(_fileCreate_fileFormats);
        eu.gloria.rt.entity.db.FileType _fileCreate_fileType = eu.gloria.rt.entity.db.FileType.RADIO;
        _fileCreate_file.setType(_fileCreate_fileType);
        try {
            java.lang.String _fileCreate__return = port.fileCreate(_fileCreate_uuidOp, _fileCreate_file);
            System.out.println("fileCreate.result=" + _fileCreate__return);

        } catch (RtiDbError e) { 
            System.out.println("Expected exception: rtiDbError has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking opCreate...");
        eu.gloria.rt.entity.db.ObservingPlan _opCreate_op = new eu.gloria.rt.entity.db.ObservingPlan();
        _opCreate_op.setId("Id1370189885");
        _opCreate_op.setUuid("Uuid-614090347");
        eu.gloria.rt.entity.db.ObservingPlanOwner _opCreate_opOwner = eu.gloria.rt.entity.db.ObservingPlanOwner.SYSTEM;
        _opCreate_op.setOwner(_opCreate_opOwner);
        eu.gloria.rt.entity.db.ObservingPlanType _opCreate_opType = eu.gloria.rt.entity.db.ObservingPlanType.OBSERVATION;
        _opCreate_op.setType(_opCreate_opType);
        _opCreate_op.setUser("User52897327");
        java.util.List<eu.gloria.rt.entity.db.File> _opCreate_opFiles = new java.util.ArrayList<eu.gloria.rt.entity.db.File>();
        eu.gloria.rt.entity.db.File _opCreate_opFilesVal1 = new eu.gloria.rt.entity.db.File();
        _opCreate_opFilesVal1.setId("Id613382024");
        _opCreate_opFilesVal1.setUuid("Uuid100248738");
        _opCreate_opFilesVal1.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-09-05T10:52:53.581+02:00"));
        eu.gloria.rt.entity.db.FileContentType _opCreate_opFilesVal1ContentType = eu.gloria.rt.entity.db.FileContentType.DARK;
        _opCreate_opFilesVal1.setContentType(_opCreate_opFilesVal1ContentType);
        java.util.List<eu.gloria.rt.entity.db.Format> _opCreate_opFilesVal1Formats = new java.util.ArrayList<eu.gloria.rt.entity.db.Format>();
        _opCreate_opFilesVal1.getFormats().addAll(_opCreate_opFilesVal1Formats);
        eu.gloria.rt.entity.db.FileType _opCreate_opFilesVal1Type = eu.gloria.rt.entity.db.FileType.VIDEO;
        _opCreate_opFilesVal1.setType(_opCreate_opFilesVal1Type);
        _opCreate_opFiles.add(_opCreate_opFilesVal1);
        _opCreate_op.getFiles().addAll(_opCreate_opFiles);
        try {
            java.lang.String _opCreate__return = port.opCreate(_opCreate_op);
            System.out.println("opCreate.result=" + _opCreate__return);

        } catch (RtiDbError e) { 
            System.out.println("Expected exception: rtiDbError has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
