package eu.gloria.rti_db;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-04-01T11:28:01.486+02:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://gloria.eu/rti_db", name = "gloria_rti_db")
@XmlSeeAlso({eu.gloria.rt.entity.db.ObjectFactory.class, ObjectFactory.class})
public interface GloriaRtiDb {

    /**
     * Gets the Observing Plan data.
     * 				@param uuid Identifier.
     * 				@return Observing Plan information
     * 				@throws RtiDbError In error case.
     * 			
     */
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "opGet", targetNamespace = "http://gloria.eu/rti_db", className = "eu.gloria.rti_db.OpGet")
    @WebMethod(action = "http://gloria.eu/rti_db/opGet")
    @ResponseWrapper(localName = "opGetResponse", targetNamespace = "http://gloria.eu/rti_db", className = "eu.gloria.rti_db.OpGetResponse")
    public eu.gloria.rt.entity.db.ObservingPlan opGet(
        @WebParam(name = "uuid", targetNamespace = "")
        java.lang.String uuid
    ) throws RtiDbError;

    /**
     * Creates a new UUID.
     * 				@return UUID.
     * 				@throws RtiDbError In error case.
     * 			
     */
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "uuidCreate", targetNamespace = "http://gloria.eu/rti_db", className = "eu.gloria.rti_db.UuidCreate")
    @WebMethod(action = "http://gloria.eu/rti_db/uuidCreate")
    @ResponseWrapper(localName = "uuidCreateResponse", targetNamespace = "http://gloria.eu/rti_db", className = "eu.gloria.rti_db.UuidCreateResponse")
    public java.lang.String uuidCreate() throws RtiDbError;

    /**
     * Adds a format.
     * 				@param uuidFile File uuid.
     * 				@param format FormatType
     * 				@throws RtiDbError In error case.
     * 			
     */
    @RequestWrapper(localName = "fileAddFormat", targetNamespace = "http://gloria.eu/rti_db", className = "eu.gloria.rti_db.FileAddFormat")
    @WebMethod(action = "http://gloria.eu/rti_db/fileAddFormat")
    @ResponseWrapper(localName = "voidResponse", targetNamespace = "http://gloria.eu/rti_db", className = "eu.gloria.rti_db.VoidResponse")
    public void fileAddFormat(
        @WebParam(name = "uuidFile", targetNamespace = "")
        java.lang.String uuidFile,
        @WebParam(name = "format", targetNamespace = "")
        eu.gloria.rt.entity.db.FileFormat format,
        @WebParam(name = "sourceURL", targetNamespace = "")
        java.lang.String sourceURL
    ) throws RtiDbError;

    /**
     * Deletes an Observing Plan.
     * 				@param uuid Observing Plan uuid.
     * 				@throws RtiDbError In error case.
     * 			
     */
    @RequestWrapper(localName = "opDelete", targetNamespace = "http://gloria.eu/rti_db", className = "eu.gloria.rti_db.OpDelete")
    @WebMethod(action = "http://gloria.eu/rti_db/opDelete")
    @ResponseWrapper(localName = "voidResponse", targetNamespace = "http://gloria.eu/rti_db", className = "eu.gloria.rti_db.VoidResponse")
    public void opDelete(
        @WebParam(name = "uuid", targetNamespace = "")
        java.lang.String uuid
    ) throws RtiDbError;

    /**
     * Deletes a file.
     * 				@param uuid File uuid.
     * 				@throws RtiDbError In error case.
     * 			
     */
    @RequestWrapper(localName = "fileDelete", targetNamespace = "http://gloria.eu/rti_db", className = "eu.gloria.rti_db.FileDelete")
    @WebMethod(action = "http://gloria.eu/rti_db/fileDelete")
    @ResponseWrapper(localName = "voidResponse", targetNamespace = "http://gloria.eu/rti_db", className = "eu.gloria.rti_db.VoidResponse")
    public void fileDelete(
        @WebParam(name = "uuid", targetNamespace = "")
        java.lang.String uuid
    ) throws RtiDbError;

    /**
     * Deletes a format.
     * 				@param uuidFile File uuid.
     * 				@param format FormatType
     * 				@throws RtiDbError In error case.
     * 			
     */
    @RequestWrapper(localName = "fileDeleteFormat", targetNamespace = "http://gloria.eu/rti_db", className = "eu.gloria.rti_db.FileDeleteFormat")
    @WebMethod(action = "http://gloria.eu/rti_db/fileDeleteFormat")
    @ResponseWrapper(localName = "voidResponse", targetNamespace = "http://gloria.eu/rti_db", className = "eu.gloria.rti_db.VoidResponse")
    public void fileDeleteFormat(
        @WebParam(name = "uuidFile", targetNamespace = "")
        java.lang.String uuidFile,
        @WebParam(name = "format", targetNamespace = "")
        eu.gloria.rt.entity.db.FileFormat format
    ) throws RtiDbError;

    /**
     * Gets the file data.
     * 				@param uuid Identifier.
     * 				@return File information
     * 				@throws RtiDbError In error case.
     * 			
     */
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "fileGet", targetNamespace = "http://gloria.eu/rti_db", className = "eu.gloria.rti_db.FileGet")
    @WebMethod(action = "http://gloria.eu/rti_db/fileGet")
    @ResponseWrapper(localName = "fileGetResponse", targetNamespace = "http://gloria.eu/rti_db", className = "eu.gloria.rti_db.FileGetResponse")
    public eu.gloria.rt.entity.db.File fileGet(
        @WebParam(name = "uuid", targetNamespace = "")
        java.lang.String uuid
    ) throws RtiDbError;

    /**
     * Creates a new File.
     * 				@param file file data.
     * 				@return UUID.
     * 				@throws RtiDbError In error case.
     * 			
     */
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "fileCreate", targetNamespace = "http://gloria.eu/rti_db", className = "eu.gloria.rti_db.FileCreate")
    @WebMethod(action = "http://gloria.eu/rti_db/fileCreate")
    @ResponseWrapper(localName = "fileCreateResponse", targetNamespace = "http://gloria.eu/rti_db", className = "eu.gloria.rti_db.FileCreateResponse")
    public java.lang.String fileCreate(
        @WebParam(name = "uuidOp", targetNamespace = "")
        java.lang.String uuidOp,
        @WebParam(name = "file", targetNamespace = "")
        eu.gloria.rt.entity.db.File file
    ) throws RtiDbError;

    /**
     * Creates a new Observing Plan.
     * 				@param op Observing Plan data.
     * 				@return UUID.
     * 				@throws RtiDbError In error case.
     * 			
     */
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "opCreate", targetNamespace = "http://gloria.eu/rti_db", className = "eu.gloria.rti_db.OpCreate")
    @WebMethod(action = "http://gloria.eu/rti_db/opCreate")
    @ResponseWrapper(localName = "opCreateResponse", targetNamespace = "http://gloria.eu/rti_db", className = "eu.gloria.rti_db.OpCreateResponse")
    public java.lang.String opCreate(
        @WebParam(name = "op", targetNamespace = "")
        eu.gloria.rt.entity.db.ObservingPlan op
    ) throws RtiDbError;
}
