
package eu.gloria.rti_db;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-04-01T11:28:01.414+02:00
 * Generated source version: 2.6.1
 * 
 */
public final class GloriaRtiDb_GloriaRtiDbSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://gloria.eu/rti_db", "gloria_rti_db");

    private GloriaRtiDb_GloriaRtiDbSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
            }

}
