
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package eu.gloria.rti_db;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-04-01T11:28:01.472+02:00
 * Generated source version: 2.6.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "gloria_rti_db",
                      portName = "gloria_rti_dbSOAP",
                      targetNamespace = "http://gloria.eu/rti_db",
                      wsdlLocation = "http://localhost:8080/RTI_DB/services/gloria_rti_dbSOAP?wsdl",
                      endpointInterface = "eu.gloria.rti_db.GloriaRtiDb")
                      
public class GloriaRtiDbImpl implements GloriaRtiDb {

    private static final Logger LOG = Logger.getLogger(GloriaRtiDbImpl.class.getName());

    /* (non-Javadoc)
     * @see eu.gloria.rti_db.GloriaRtiDb#opGet(java.lang.String  uuid )*
     */
    public eu.gloria.rt.entity.db.ObservingPlan opGet(java.lang.String uuid) throws RtiDbError    { 
        LOG.info("Executing operation opGet");
        System.out.println(uuid);
        /*try {
            eu.gloria.rt.entity.db.ObservingPlan _return = new eu.gloria.rt.entity.db.ObservingPlan();
            _return.setId("Id1195042439");
            _return.setUuid("Uuid-1734425269");
            eu.gloria.rt.entity.db.ObservingPlanOwner _returnOwner = eu.gloria.rt.entity.db.ObservingPlanOwner.SYSTEM;
            _return.setOwner(_returnOwner);
            eu.gloria.rt.entity.db.ObservingPlanType _returnType = eu.gloria.rt.entity.db.ObservingPlanType.OBSERVATION;
            _return.setType(_returnType);
            _return.setUser("User-1652600018");
            java.util.List<eu.gloria.rt.entity.db.File> _returnFiles = new java.util.ArrayList<eu.gloria.rt.entity.db.File>();
            eu.gloria.rt.entity.db.File _returnFilesVal1 = new eu.gloria.rt.entity.db.File();
            _returnFilesVal1.setId("Id-1166250545");
            _returnFilesVal1.setUuid("Uuid1923792055");
            _returnFilesVal1.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T17:11:17.913+01:00"));
            eu.gloria.rt.entity.db.FileContentType _returnFilesVal1ContentType = eu.gloria.rt.entity.db.FileContentType.OBSERVATION;
            _returnFilesVal1.setContentType(_returnFilesVal1ContentType);
            java.util.List<eu.gloria.rt.entity.db.FileFormat> _returnFilesVal1Formats = new java.util.ArrayList<eu.gloria.rt.entity.db.FileFormat>();
            _returnFilesVal1.getFormats().addAll(_returnFilesVal1Formats);
            eu.gloria.rt.entity.db.FileType _returnFilesVal1Type = eu.gloria.rt.entity.db.FileType.RADIO;
            _returnFilesVal1.setType(_returnFilesVal1Type);
            _returnFilesVal1.setUrl("Url1833850087");
            _returnFiles.add(_returnFilesVal1);
            _return.getFiles().addAll(_returnFiles);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }*/
        //throw new RtiDbError("rtiDbError...");
        
        return null;
    }

    /* (non-Javadoc)
     * @see eu.gloria.rti_db.GloriaRtiDb#uuidCreate(*
     */
    public java.lang.String uuidCreate() throws RtiDbError    { 
        LOG.info("Executing operation uuidCreate");
        try {
            java.lang.String _return = "_return-949782066";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new RtiDbError("rtiDbError...");
    }

    /* (non-Javadoc)
     * @see eu.gloria.rti_db.GloriaRtiDb#fileAddFormat(java.lang.String  uuidFile ,)eu.gloria.rt.entity.db.FileFormat  format ,)java.lang.String  sourceURL )*
     */
    public void fileAddFormat(java.lang.String uuidFile,eu.gloria.rt.entity.db.FileFormat format,java.lang.String sourceURL) throws RtiDbError    { 
        LOG.info("Executing operation fileAddFormat");
        System.out.println(uuidFile);
        System.out.println(format);
        System.out.println(sourceURL);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new RtiDbError("rtiDbError...");
    }

    /* (non-Javadoc)
     * @see eu.gloria.rti_db.GloriaRtiDb#opDelete(java.lang.String  uuid )*
     */
    public void opDelete(java.lang.String uuid) throws RtiDbError    { 
        LOG.info("Executing operation opDelete");
        System.out.println(uuid);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new RtiDbError("rtiDbError...");
    }

    /* (non-Javadoc)
     * @see eu.gloria.rti_db.GloriaRtiDb#fileDelete(java.lang.String  uuid )*
     */
    public void fileDelete(java.lang.String uuid) throws RtiDbError    { 
        LOG.info("Executing operation fileDelete");
        System.out.println(uuid);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new RtiDbError("rtiDbError...");
    }

    /* (non-Javadoc)
     * @see eu.gloria.rti_db.GloriaRtiDb#fileDeleteFormat(java.lang.String  uuidFile ,)eu.gloria.rt.entity.db.FileFormat  format )*
     */
    public void fileDeleteFormat(java.lang.String uuidFile,eu.gloria.rt.entity.db.FileFormat format) throws RtiDbError    { 
        LOG.info("Executing operation fileDeleteFormat");
        System.out.println(uuidFile);
        System.out.println(format);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new RtiDbError("rtiDbError...");
    }

    /* (non-Javadoc)
     * @see eu.gloria.rti_db.GloriaRtiDb#fileGet(java.lang.String  uuid )*
     */
    public eu.gloria.rt.entity.db.File fileGet(java.lang.String uuid) throws RtiDbError    { 
        /*LOG.info("Executing operation fileGet");
        System.out.println(uuid);
        try {
            eu.gloria.rt.entity.db.File _return = new eu.gloria.rt.entity.db.File();
            _return.setId("Id1687720576");
            _return.setUuid("Uuid-1859772950");
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T17:11:17.916+01:00"));
            eu.gloria.rt.entity.db.FileContentType _returnContentType = eu.gloria.rt.entity.db.FileContentType.OBSERVATION;
            _return.setContentType(_returnContentType);
            java.util.List<eu.gloria.rt.entity.db.FileFormat> _returnFormats = new java.util.ArrayList<eu.gloria.rt.entity.db.FileFormat>();
            eu.gloria.rt.entity.db.FileFormat _returnFormatsVal1 = eu.gloria.rt.entity.db.FileFormat.FITS;
            _returnFormats.add(_returnFormatsVal1);
            _return.getFormats().addAll(_returnFormats);
            eu.gloria.rt.entity.db.FileType _returnType = eu.gloria.rt.entity.db.FileType.RADIO;
            _return.setType(_returnType);
            _return.setUrl("Url-29091927");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }*/
        //throw new RtiDbError("rtiDbError...");
    	
    	return null;
    }

    /* (non-Javadoc)
     * @see eu.gloria.rti_db.GloriaRtiDb#fileCreate(java.lang.String  uuidOp ,)eu.gloria.rt.entity.db.File  file )*
     */
    public java.lang.String fileCreate(java.lang.String uuidOp,eu.gloria.rt.entity.db.File file) throws RtiDbError    { 
        LOG.info("Executing operation fileCreate");
        System.out.println(uuidOp);
        System.out.println(file);
        try {
            java.lang.String _return = "_return1665450177";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new RtiDbError("rtiDbError...");
    }

    /* (non-Javadoc)
     * @see eu.gloria.rti_db.GloriaRtiDb#opCreate(eu.gloria.rt.entity.db.ObservingPlan  op )*
     */
    public java.lang.String opCreate(eu.gloria.rt.entity.db.ObservingPlan op) throws RtiDbError    { 
        LOG.info("Executing operation opCreate");
        System.out.println(op);
        try {
            java.lang.String _return = "_return-1527359629";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new RtiDbError("rtiDbError...");
    }

}
