package eu.gloria.rti_db;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-04-01T11:28:01.493+02:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "gloria_rti_db", 
                  wsdlLocation = "http://localhost:8080/RTI_DB/services/gloria_rti_dbSOAP?wsdl",
                  targetNamespace = "http://gloria.eu/rti_db") 
public class GloriaRtiDb_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://gloria.eu/rti_db", "gloria_rti_db");
    public final static QName GloriaRtiDbSOAP = new QName("http://gloria.eu/rti_db", "gloria_rti_dbSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/RTI_DB/services/gloria_rti_dbSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GloriaRtiDb_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/RTI_DB/services/gloria_rti_dbSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GloriaRtiDb_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GloriaRtiDb_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GloriaRtiDb_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GloriaRtiDb
     */
    @WebEndpoint(name = "gloria_rti_dbSOAP")
    public GloriaRtiDb getGloriaRtiDbSOAP() {
        return super.getPort(GloriaRtiDbSOAP, GloriaRtiDb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GloriaRtiDb
     */
    @WebEndpoint(name = "gloria_rti_dbSOAP")
    public GloriaRtiDb getGloriaRtiDbSOAP(WebServiceFeature... features) {
        return super.getPort(GloriaRtiDbSOAP, GloriaRtiDb.class, features);
    }

}
