
package eu.gloria.rti_db;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-04-01T11:28:01.465+02:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "errorDetail", targetNamespace = "http://gloria.eu/rti_db")
public class RtiDbError extends Exception {
    
    private eu.gloria.rti_db.ErrorDetail errorDetail;

    public RtiDbError() {
        super();
    }
    
    public RtiDbError(String message) {
        super(message);
    }
    
    public RtiDbError(String message, Throwable cause) {
        super(message, cause);
    }

    public RtiDbError(String message, eu.gloria.rti_db.ErrorDetail errorDetail) {
        super(message);
        this.errorDetail = errorDetail;
    }

    public RtiDbError(String message, eu.gloria.rti_db.ErrorDetail errorDetail, Throwable cause) {
        super(message, cause);
        this.errorDetail = errorDetail;
    }

    public eu.gloria.rti_db.ErrorDetail getFaultInfo() {
        return this.errorDetail;
    }
}
