/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_gloria_rt_catalogue_libnova_LibNovaJNI */

#ifndef _Included_eu_gloria_rt_catalogue_libnova_LibNovaJNI
#define _Included_eu_gloria_rt_catalogue_libnova_LibNovaJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_gloria_rt_catalogue_libnova_LibNovaJNI
 * Method:    getObjectInfo
 * Signature: (Leu/gloria/rt/catalogue/libnova/LibNovaJNIInput;Leu/gloria/rt/catalogue/libnova/LibNovaJNIObjInfo;)V
 */
JNIEXPORT void JNICALL Java_eu_gloria_rt_catalogue_libnova_LibNovaJNI_getObjectInfo
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     eu_gloria_rt_catalogue_libnova_LibNovaJNI
 * Method:    getAltazByRadec
 * Signature: (Leu/gloria/rt/catalogue/libnova/LibNovaObserver;Leu/gloria/rt/catalogue/libnova/LibNovaZoneDate;Leu/gloria/rt/catalogue/libnova/LibNovaRaDecJ2000;Leu/gloria/rt/catalogue/libnova/LibNovaAltaz;Leu/gloria/rt/catalogue/libnova/LibNovaReturnedInfo;)V
 */
JNIEXPORT void JNICALL Java_eu_gloria_rt_catalogue_libnova_LibNovaJNI_getAltazByRadec
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     eu_gloria_rt_catalogue_libnova_LibNovaJNI
 * Method:    getAngularDistance
 * Signature: (Leu/gloria/rt/catalogue/libnova/LibNovaRaDecJ2000;Leu/gloria/rt/catalogue/libnova/LibNovaRaDecJ2000;Leu/gloria/rt/catalogue/libnova/LibNovaAngularDistance;Leu/gloria/rt/catalogue/libnova/LibNovaReturnedInfo;)V
 */
JNIEXPORT void JNICALL Java_eu_gloria_rt_catalogue_libnova_LibNovaJNI_getAngularDistance
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     eu_gloria_rt_catalogue_libnova_LibNovaJNI
 * Method:    getRTS
 * Signature: (Leu/gloria/rt/catalogue/libnova/LibNovaObserver;Leu/gloria/rt/catalogue/libnova/LibNovaZoneDate;Ljava/lang/String;Leu/gloria/rt/catalogue/libnova/LibNovaRTSInfo;Leu/gloria/rt/catalogue/libnova/LibNovaReturnedInfo;)V
 */
JNIEXPORT void JNICALL Java_eu_gloria_rt_catalogue_libnova_LibNovaJNI_getRTS
  (JNIEnv *, jobject, jobject, jobject, jstring, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
